### PR TITLE
Only query wins and losses for ranked matches

### PR DESCRIPTION
**Pull request by Similacrest**
Use only games with MP_RANKED game type for wins and losses calculation.

Not tested yet, as I haven't set a dev environment up and can't see example data in a table.

### CODE REVIEW

**Comment by Similacrest** [comment]
OK, wait, i think the join is not that simple, it has composite keys

**Comment by kbasten** [comment]
Nice update! However, this returns null for people that have not played ranked games. Can you either make the query return 0, or update the logic to fix this?

**Comment by djetelina** [comment]
If it's slecting null for each and as a whole, I'd say that's fine, as it did that with former query too.

**Comment by kbasten** [comment]
The join makes it null, it used to return 0 for people with no games played.

**Comment by Similacrest** [comment]
OK, will fix

**Comment by Similacrest** [comment]
that should do it

**Comment by kbasten** [comment]
Very nice, thank you

**Pull request merged**
